options:
  docker: true
  size: 2x
pipelines:
  pull-requests:
    'master':
      - step:
          name: Atlassian Security Secrets Scan
          script:
            - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          image: 'node:14.16'
          name: 'Linter'
          script: 
            - npm config set dev true 
            - npm config set npat true
            - npm i --no-progress
            - npx eslint . --ext .js,.jsx,.ts,.tsx
      - step:
          name: 'Test'
          image: 'node:14.16'
          script:
            - npm i --no-progress
            - npm i -g gulp
            - sh ./post-install.sh
            - npm run test:unit
  branches:
    alpha:
    - step: 
        name: 'Fetch NPM dependencies'
        image: node:14.16
        script:
          - npm ci --only=production
          - npm audit fix --production
        caches:
          - nodemodules
        artifacts:
          - node_modules/**
    - step:
        name: "Build & Push Docker image"
        image: python:3.9-alpine
        script:
          - pip3 install -U awscli
          - export REPO=$DOCKER_REPO_URL/kidsloop-pdf-service
          - export SEMVAR=$(node -e "const p = require('./package.json'); console.log(p.version);")
          - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $DOCKER_REPO_URL
          - docker build -f Dockerfile -t pdf-service --target build .
          - docker tag pdf-service:latest $REPO:alpha
          - docker tag pdf-service:$SEMVAR $REPO:$SEMVAR
          - docker push $REPO:alpha
          - docker push $REPO:$SEMVAR
        services:
          - docker
        caches:
          - docker
        size: 2x
    production:
    - step: 
        name: 'Fetch NPM dependencies'
        image: node:14.16
        script:
          - npm ci --only=production
          - npm audit fix
        caches:
          - nodemodules
        artifacts:
          - node_modules/**
    - step:
        name: "Build & Push Docker image"
        image: python:3.9-alpine
        script:
          - pip3 install -U awscli
          - export BRANCH_TAG=$(echo "$BITBUCKET_BRANCH" | sed -E 's/([^0-9a-zA-Z]+)/-/g' | awk '{print tolower($0)}')
          - export REPO=$DOCKER_REPO_URL/kidsloop-pdf-service
          - export COMMIT_TAG=$(echo $BITBUCKET_COMMIT | cut -c1-7)
          - export SEMVAR=$(node -e "const p = require('./package.json'); console.log(p.version);")
          - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $DOCKER_REPO_URL
          - docker build -t pdf-service -f Dockerfile --target build .
          - docker tag pdf-service:latest $REPO:$BRANCH_TAG-$COMMIT_TAG
          - docker tag pdf-service:latest $REPO:$SEMVAR-$COMMIT_TAG
          - docker tag pdf-service:latest $REPO:$SEMVAR
          - docker push $REPO:$BRANCH_TAG-$COMMIT_TAG
          - docker push $REPO:$SEMVAR-$COMMIT_TAG
          - docker push $REPO:$SEMVAR
        services:
          - docker
        size: 2x

definitions:
  caches:
    nodemodules: ./node_modules
  services:
    docker:
      memory: 4096