options:
  docker: true
  size: 2x
pipelines:
  pull-requests:
    'master':
      - step:
          image: 'node:lts'
          name: 'Linter'
          script: 
            - npm config set dev true 
            - npm config set npat true
            - npm i --no-progress
            - npx eslint . --ext .js,.jsx,.ts,.tsx
  branches:
    alpha:
    - step:
        name: "Build & Push Docker image"
        image: python:3.9-alpine
        script:
          - pip3 install -U awscli
          - export REPO=$DOCKER_REPO_URL/kidsloop-pdf-service
          - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $DOCKER_REPO_URL
          - docker build -f Dockerfile -t pdf-service --target build .
          - docker tag pdf-service:latest $REPO:alpha
          - docker push $REPO:alpha
        services:
          - docker
        caches:
          - docker
        size: 2x
    production:
    - step:
        name: "Build & Push Docker image"
        image: python:3.9-alpine
        script:
          - pip3 install -U awscli
          - export BRANCH_TAG=$(echo "$BITBUCKET_BRANCH" | sed -E 's/([^0-9a-zA-Z]+)/-/g' | awk '{print tolower($0)}')
          - export REPO=$DOCKER_REPO_URL/kidsloop-pdf-service
          - export COMMIT_TAG=$(echo $BITBUCKET_COMMIT | cut -c1-7)
          - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $DOCKER_REPO_URL
          - docker build -t pdf-service -f Dockerfile --target release .
          - docker tag pdf-service:latest $REPO:$BRANCH_TAG-$COMMIT_TAG
          - docker push $REPO:$BRANCH_TAG-$COMMIT_TAG
        services:
          - docker
        size: 2x

definitions:
  caches:
    nodemodules: ./node_modules
  services:
    docker:
      memory: 4096