name: Docker Image CI

on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master, actions ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Configure NodeJS
    - uses: actions/setup-node@v2
      with:
        node-version: '16.6'

    - name: Install Dependencies
      run: npm ci

    - name: Run Unit Tests
      run: npm run test:unit
      
#     - name: Prepare For Packaging
#       run: |
#         rm -rf ./node_modules
#         npm ci --production=only      
      
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag ${{github.repository.name}}:$(head -c 8 <<< ${{github.sha}})
