name: Docker Image CI

on:
  push:
    branches: [ master, actions, "audit-fixes" ]
  pull_request:
    branches: [ master, actions, "audit-fixes" ]

jobs:

  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Configure NodeJS
    - uses: actions/setup-node@v2
      env:
        NODE_AUTH_TOKEN: ${{secrets.KL_PACKAGES_PAT}}
      with:
        node-version: '16.6'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@kidsloop-global'
    - name: Install Dependencies
      run: npm ci

    - name: Run Unit Tests
      run: npm run test:unit
  
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Configure NodeJS
    - uses: actions/setup-node@v2
      env:
        NODE_AUTH_TOKEN: ${{secrets.KL_PACKAGES_PAT}}
      with:
        node-version: '16.6'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@kidsloop-global'
    - name: Install Dependencies
      run: npm ci --production=only

    - name: Build
      run: npm run build

    - name: Create Image
      run: docker build . --file Dockerfile --tag ${{github.repository.name}}:$(head -c 8 <<< ${{github.sha}})
